Repository JetBrains/jewel, pull requests merged in 2023-12, with the labels that each got.

#267 Update IJP 233
  gradle/libs.versions.toml
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
Labels: maintenance

#266 Fix tree colours being mixed up
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLazyTreeStyling.kt
Labels: bug

#270 Create Slider component
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/BridgeSliderStyling.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSliderStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Slider.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Button.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Slider.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/SliderStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: new component

#272 Update IJP to 233.11799.300 (233.1)
  gradle/libs.versions.toml
Labels: maintenance

#269 Dropdown support for leading icons
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/KeyActions.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiMenuStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/TitleBarView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Dropdowns.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Links.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/MenuStyling.kt
Labels: feature, consistency

#278 Update IJ 233 to 233.13135.103
  gradle/libs.versions.toml
Labels: maintenance

#276 Extend TabStrip API to support custom behaviours
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/TabStyling.kt
Labels: feature, consistency
