Repository JetBrains/jewel, pull requests merged in 2023-11, with the labels that each got.

#230 Remove LabelledTextField and its styling
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLabelledTextFieldStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/LabelledTextField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LabelledTextFieldStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: api

#241 Update IJP 233 to 233.11555.11-EAP-SNAPSHOT
  gradle/libs.versions.toml
Labels: bridge

#244 Fix error appearing when selectedKeys contain invalid key
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyListScope.kt
  foundation/src/test/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumnTest.kt
Labels: bug

#252 Update IJ Platform 23.3
  .gitignore
  .idea/runConfigurations/Check_IJP_version__23_2_.xml
  .idea/runConfigurations/Check_IJP_version__23_3_.xml
  gradle/libs.versions.toml
Labels: maintenance
