Repository JetBrains/jewel, pull requests merged in 2024-10, with the labels that each got.

#621 Update Compose to 1.7.0-rc01
  gradle/libs.versions.toml
Labels: maintenance

#625 Fix keyboard event handling in BasicSelectableLazyColumn
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/BasicSelectableLazyColumn.kt
Labels: bug

#628 Move to ijp 243
  .gitignore
  README.md
  build.gradle.kts
  buildSrc/src/main/kotlin/jewel-check-public-api.gradle.kts
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/demodata/AndroidStudioReleases.kt
  decorated-window/build.gradle.kts
  foundation/build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  ide-laf-bridge-tests/build.gradle.kts
  ide-laf-bridge/build.gradle.kts
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/ScrollbarHelper.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/SwingBridgeTheme.kt
  int-ui/int-ui-decorated-window/build.gradle.kts
  int-ui/int-ui-standalone/build.gradle.kts
  markdown/core/build.gradle.kts
  markdown/extension/autolink/build.gradle.kts
  markdown/extension/gfm-alerts/build.gradle.kts
  markdown/ide-laf-bridge-styling/build.gradle.kts
  markdown/int-ui-standalone-styling/build.gradle.kts
  samples/ide-plugin/build.gradle.kts
  samples/standalone/build.gradle.kts
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/JewelReadme.kt
  ui/api/ui.api
  ui/build.gradle.kts
Labels: maintenance

#634 Add Throubleshooting section with a fix for Git Pre-push hook
  README.md
Labels: documentation

#638 Upgrade Compose to 1.7.0 stable
  gradle/libs.versions.toml
Labels: maintenance

#635 Fix missing ⬇️ event on editable ComboBox
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
  ui-tests/src/test/kotlin/ListComboBoxUiTest.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/EditableComboBox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt
Labels: bug, regression

#642 Remove deprecated Kotlin build flag
  gradle.properties
Labels: cleanup

#647 Update IJP to 2024.1.7 (241.19416.15)
  gradle/libs.versions.toml
Labels: maintenance

#644 Add enabled parameter to Tooltip
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tooltips.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tooltip.kt
Labels: feature

#652 Update IJP to 243 EAP 6 (243.20847.40)
  gradle/libs.versions.toml
  ui/api/ui.api
Labels: maintenance

#655 Make addComposeTab's tab title nullable
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/ToolWindowExtensions.kt
Labels: api

#656 Add all scrollbar parameters to scrollable containers
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ScrollableContainer.kt
Labels: api

#660 Use transparent background for disabled TextField/TextArea
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
Labels: bug

#662 Polish TextField, TextArea, and RadioButton
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiRadioButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextAreaStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextAreas.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
Labels: consistency

#663 Bump IJP 243 to EAP 7 (243.21155.17)
  gradle/libs.versions.toml
Labels: maintenance

#665 Force Skiko to 0.8.17
  build.gradle.kts
Labels: bug
