Repository JetBrains/jewel, pull requests merged in 2024-04, with the labels that each got.

#341 Add an autolink extension for Markdown
  gradle/libs.versions.toml
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownProcessorExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/extension/autolink/api/autolink.api
  markdown/extension/autolink/build.gradle.kts
  markdown/extension/autolink/src/main/kotlin/org/jetbrains/jewel/markdown/extension/autolink/AutolinkProcessorExtension.kt
  markdown/extension/autolink/src/test/kotlin/org/jetbrains/jewel/markdown/extension/autolink/AutolinkProcessorExtensionTest.kt
  samples/standalone/build.gradle.kts
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
  settings.gradle.kts
Labels: feature

#338 Clean up Commonmark API conventions
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/InlineMarkdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/MarkdownBlock.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownStyling.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingExtraTest.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/TestUtils.kt
Labels: cleanup

#343 Update Compose to 1.6.10-dev1561
  gradle/libs.versions.toml
Labels: maintenance

#342 Add dialog sample to ide-plugin
  .idea/runConfigurations/IDE_sample.xml
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/dialog/JewelDemoAction.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/dialog/WizardDialogWrapper.kt
  samples/ide-plugin/src/main/resources/META-INF/plugin.xml
Labels: feature

#350 Fix potential recomposition loops
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Checkbox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/RadioButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/PainterProvider.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
Labels: bug, cleanup

#349 Update IJP to 241.14494.240-EAP-SNAPSHOT
  gradle/libs.versions.toml
Labels: maintenance

#353 Add theme name to ThemeDefinition and JewelTheme
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/JewelTheme.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/ThemeDefinition.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/MarkdownViewer.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: feature

#360 Fix crash in CircularProgressIndicator when switching themes
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/CircularProgressIndicator.kt
Labels: bug

#361 Fix menu dividers in bridge
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiMenuStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/TitleBarView.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Dropdown.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/MenuStyling.kt
Labels: bug, consistency

#362 Fix dividers not showing up in old UI themes
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
Labels: bug

#364 Use connect() instead of simpleConnect()
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/Bridge.kt
Labels: cleanup

#365 Fix text colour in Markdown (bridge)
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/styling/MarkdownBridgeStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/MarkdownPreview.kt
Labels: bug, bridge

#366 Add onTextClick to MarkdownBlockRenderer
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/MarkdownBlockRendererExtensions.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/MarkdownBlockRendererExtensions.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/MarkdownPreview.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Checkbox.kt
Labels: bug

#367 Add Markdown styling to theme
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/Markdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownBlockRendererExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownBlockRenderer.kt
  markdown/extension/gfm-alerts/api/gfm-alerts.api
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertBlockRenderer.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/BridgeMarkdownBlockRendererExtensions.kt
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/MarkdownBlockRendererExtensions.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/IntUiMarkdownBlockRendererExtensions.kt
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/MarkdownBlockRendererExtensions.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/MarkdownPreview.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: feature

#372 Update onFocusChanged in SelectableLazyColumn
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
Labels: bug
