Repository JetBrains/jewel, pull requests merged in 2024-11, with the labels that each got.

#672 Keep trailing empty lines at the end of the Markdown code block
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
Labels: bug

#670 Split IntUiBridge into separate files according to components
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeButton.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeCheckbox.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeChip.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeComboBox.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeDivider.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeDropdown.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeGroupHeader.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeLazyTree.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeLink.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeMenu.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgePopupContainer.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeProgress.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeRadioButton.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSegmentedControl.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSelectableLazyColumn.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSimpleListItem.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSlider.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTab.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeText.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTextArea.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTextField.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTooltip.kt
Labels: maintenance

#673 Allow configuring the ComposePanel via JewelComposePanel APIs
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
Labels: feature

#667 Fix SplitLayout divider positioning error
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SplitLayout.kt
Labels: bug

#674 Fix Dropdown disabled colors
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Dropdown.kt
Labels: bug

#675 Change the New UI detection logic in the bridge
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
Labels: consistency, bridge

#693 Bump Compose 1.7.0 -> 1.7.1
  gradle/libs.versions.toml
Labels: maintenance

#692 In ListComboBox prevents caret from moving on key up/down pressed
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/EditableComboBox.kt
Labels: consistency

#627 Add ListComboBox
  .idea/ktlint-plugin.xml
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumn.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/BasicLazyTree.kt
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeButton.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeCheckbox.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeChip.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeComboBox.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeDivider.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeDropdown.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeGroupHeader.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeLazyTree.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeLink.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeMenu.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgePopupContainer.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeProgress.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeRadioButton.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSegmentedControl.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSelectableLazyColumn.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSimpleListItem.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeSlider.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTab.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeText.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTextArea.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTextField.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeTooltip.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiComboBoxStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLazyTreeStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiMenuStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiPopupContainerStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSelectableLazyColumnStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSimpleListItemStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/build.gradle.kts
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Dropdowns.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  settings.gradle.kts
  ui-tests/build.gradle.kts
  ui-tests/src/test/kotlin/ListComboBoxUiTest.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ComboBox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/EditableComboBox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/LazyTree.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ListComboBox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/PopupContainer.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SimpleListItem.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/ComboBoxStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LazyTreeStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/PopupContainerStyle.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/SelectableLazyColumnStyle.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/SimpleListItemStyle.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: new component, epic

#689 InformationBanner PoC
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeBanner.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUIBannerStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentsShowcaseTab2.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindowFactory.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Banners.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/ComponentsViewModel.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Banner.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/BannerStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: new component

#697 Add all remaing banners
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeBanner.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUIBannerStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentsShowcaseTab2.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindowFactory.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Banners.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Banner.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/BannerStyling.kt
Labels: consistency

#700 Fixup after dividers
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/ComponentsView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Divider.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/GroupHeader.kt
Labels: cleanup

#688 Banners
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridgeBanner.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUIBannerStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Banners.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/ComponentsViewModel.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Banner.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/BannerStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: new component, epic

#704 Tune logging
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
Labels: cleanup

#705 Fix indeterminate state not working in Checkboxes
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/state/ToggleableComponentState.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Checkboxes.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Checkbox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/CheckboxStyling.kt
Labels: bug
