Repository JetBrains/jewel, pull requests merged in 2024-07, with the labels that each got.

#420 Fix default button focus outline & chip colors
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/BridgeGlobalMetrics.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiChipStyling.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/Outline.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Button.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Chip.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/ButtonStyling.kt
Labels: consistency

#421 Upgrade to Compose 1.7.0-dev1703
  foundation/api/foundation.api
  gradle/libs.versions.toml
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/NoIndication.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/IconButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: maintenance

#423 Fix soft line breaks treated as hard line breaks
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
Labels: bug

#432 Made icon generation more maintainable
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/icon-keys-generator.gradle.kts
  settings.gradle.kts
  ui/build.gradle.kts
Labels: documentation, maintenance

#434 Use IJ distributions for compilation of sample
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/jewel.gradle.kts
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/ideversion/ApiIdeaReleasesItem.kt
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/ideversion/CheckIdeaVersionTask.kt
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/ideversion/IJPVersionsFetcher.kt
  gradle.properties
  gradle/libs.versions.toml
  samples/ide-plugin/build.gradle.kts
  samples/standalone/build.gradle.kts
  ui/api/ui.api
Labels: maintenance

#436 Fix MD code font in dark standalone theme
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
Labels: bug, standalone

#435 Fix publication issues
  buildSrc/src/main/kotlin/icon-keys-generator.gradle.kts
  buildSrc/src/main/kotlin/intellij-theme-generator.gradle.kts
  buildSrc/src/main/kotlin/jewel-publish.gradle.kts
  int-ui/int-ui-standalone/build.gradle.kts
Labels: bug

#439 Replace icon paths with keys
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeResourceResolver.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiCheckboxStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiDropdownStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLazyTreeStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLinkStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiMenuStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiRadioButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
  samples/standalone/build.gradle.kts
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Checkbox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Dropdown.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Icon.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/LazyTree.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Link.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/PlatformIcon.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/RadioButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/CheckboxStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/DropdownStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LazyTreeStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LinkStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/MenuStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/RadioButtonStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/TabStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
Labels: feature

#438 Refresh Jewel Markdown README
  markdown/README.md
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: documentation, maintenance, markdown

#440 Fix snapshot publishing version
  buildSrc/src/main/kotlin/jewel-publish.gradle.kts
Labels: bug

#441 Cleanup icons in samples
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/reflection/Views.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/ComponentsView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/TitleBarView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/WelcomeView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Dropdowns.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Icons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/View.kt
  samples/standalone/src/main/resources/expui/icons/close.svg
  samples/standalone/src/main/resources/expui/icons/closeHovered.svg
  samples/standalone/src/main/resources/expui/icons/closeHovered_dark.svg
  samples/standalone/src/main/resources/expui/icons/close_dark.svg
  samples/standalone/src/main/resources/expui/icons/search.svg
  samples/standalone/src/main/resources/expui/icons/search_dark.svg
  samples/standalone/src/main/resources/icons/close.svg
  samples/standalone/src/main/resources/icons/closeHovered.svg
  samples/standalone/src/main/resources/icons/cwmAccess.svg
  samples/standalone/src/main/resources/icons/cwmAccess@20x20.svg
  samples/standalone/src/main/resources/icons/cwmAccess@20x20_dark.svg
  samples/standalone/src/main/resources/icons/cwmAccess_dark.svg
  samples/standalone/src/main/resources/icons/folderIcon.svg
  samples/standalone/src/main/resources/icons/folderIcon_dark.svg
  samples/standalone/src/main/resources/icons/gradleIcon.svg
  samples/standalone/src/main/resources/icons/gradleIcon_dark.svg
  samples/standalone/src/main/resources/icons/kotlin.svg
  samples/standalone/src/main/resources/icons/nodejsIcon.svg
  samples/standalone/src/main/resources/icons/restart.svg
  samples/standalone/src/main/resources/icons/restart_dark.svg
  samples/standalone/src/main/resources/icons/search.svg
  samples/standalone/src/main/resources/icons/search@20x20.svg
  samples/standalone/src/main/resources/icons/search@20x20_dark.svg
  samples/standalone/src/main/resources/icons/search_dark.svg
  samples/standalone/src/main/resources/icons/settings.svg
  samples/standalone/src/main/resources/icons/settings@20x20.svg
  samples/standalone/src/main/resources/icons/settings@20x20_dark.svg
  samples/standalone/src/main/resources/icons/settings_dark.svg
  samples/standalone/src/main/resources/images/New UI Image.png
  samples/standalone/src/main/resources/images/New UI Image@2x.png
  samples/standalone/src/main/resources/images/android-head.svg
  samples/standalone/src/main/resources/images/android-head_dark.svg
  samples/standalone/src/main/resources/images/android-studio.svg
  samples/standalone/src/main/resources/images/help.svg
  samples/standalone/src/main/resources/images/help_dark.svg
  samples/standalone/src/main/resources/organization/avatar.svg
  samples/standalone/src/main/resources/organization/dashboard.svg
  samples/standalone/src/main/resources/organization/notifications.svg
  samples/standalone/src/main/resources/organization/projects.svg
  samples/standalone/src/main/resources/organization/teams.svg
  samples/standalone/src/main/resources/organization/toolbox.svg
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Icon.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
Labels: cleanup

#444 Allow customizing the CommonMark Parser
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownParserFactory.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
Labels: api, markdown

#446 Update 242 IJ Platform to beta 1
  buildSrc/src/main/kotlin/icon-keys-generator.gradle.kts
  gradle/libs.versions.toml
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/icon/IntelliJIconKey.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Tabs.kt
Labels: maintenance

#447 Improve icon buttons by making them optionally focusable
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiIconButtonStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/IconButton.kt
Labels: feature

#442 Minor updates to the build files
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/jewel.gradle.kts
  samples/standalone/build.gradle.kts
Labels: cleanup

#448 Fix colour keys in bridge
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/BridgeSliderStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleaseChannel.kt
Labels: bug, bridge

#449 Add Icon action button
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/IconActionButton.kt
Labels: new component

#450 Add ActionButton component
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/ActionButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/IconActionButton.kt
Labels: new component

#387 Add segmented controls
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSegmentedControlButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSegmentedControlStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/SegmentedControls.kt
  samples/standalone/src/main/resources/icons/components/segmentedControl.svg
  samples/standalone/src/main/resources/icons/components/segmentedControl_dark.svg
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/DefaultComponentStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SegmentedControl.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SegmentedControlButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/SegmentedControlButtonStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/SegmentedControlStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/theme/JewelTheme.kt
Labels: feature, new component

#451 Remove ktlint IJ plugin from required plugins
  .idea/externalDependencies.xml
Labels: maintenance

#455 Implement proper Markdown link styling
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/Markdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownStyling.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/BridgeMarkdownStyling.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/MarkdownView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/JewelReadme.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: consistency, api

#456 Be more specific in IDE sample run config
  .idea/runConfigurations/IDE_sample.xml
Labels: bug

#458 Fix Markdown rendering issues
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/InlineMarkdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/MarkdownBlock.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/WithInlineMarkdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/WithTextContent.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownInlineProcessorExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownInlineRendererExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownProcessorExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/MarkdownRendererExtension.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/ProcessingUtil.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultInlineMarkdownRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/InlineMarkdownRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownStyling.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingExtraTest.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/TestUtils.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessorOptimizeEditsTest.kt
  markdown/extension/autolink/api/autolink.api
  markdown/extension/autolink/src/main/kotlin/org/jetbrains/jewel/markdown/extension/autolink/AutolinkProcessorExtension.kt
  markdown/extension/gfm-alerts/api/gfm-alerts.api
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertProcessorExtension.kt
  markdown/extension/gfm-alerts/src/test/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertBlockExtensionTest.kt
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/BridgeMarkdownBlockRendererExtensions.kt
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/BridgeMarkdownStyling.kt
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/IntUiMarkdownBlockRendererExtensions.kt
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/JewelReadme.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: markdown

#461 Improve borders sample page
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Borders.kt
Labels: feature

#460 Update README for 0.20.0
  README.md
Labels: documentation

#488 Move (Icon)ActionButton to the right package
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ActionButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/IconActionButton.kt
Labels: api, cleanup

#487 Update target IJP to 242.20224.91
  gradle/libs.versions.toml
Labels: maintenance

#486 Rename palette entry grey -> gray
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/theme/IntUiThemeDescriptorReader.kt
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/ThemeColorPalette.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/BridgeThemeColorPalette.kt
  int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiTitleBarStyling.kt
  int-ui/int-ui-standalone/build.gradle.kts
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiCheckboxStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiChipStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiDividerStyle.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiDropdownStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiGroupHeaderStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiHorizontalProgressBarStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiIconButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLazyTreeStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLinkStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiMenuStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiRadioButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSegmentedControlButtonStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSegmentedControlStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiSliderStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextAreaStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTooltipStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiGlobalColors.kt
  markdown/README.md
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Borders.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
Labels: consistency, api

#490 Remove TextStyles from stylings
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiDropdownStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLinkStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextAreaStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Link.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/DropdownStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/InputFieldStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LinkStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/TextAreaStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/TextFieldStyling.kt
Labels: api, cleanup

#468 Upgrade IJP Gradle plugin to 2.0.0-rc1
  gradle/libs.versions.toml
Labels: maintenance

#492 Add underline style to links
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiLinkStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Links.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Link.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/LinkStyling.kt
Labels: feature, api

#498 Lower target JDK for 242
  .idea/runConfigurations/Check_IJP_updates.xml
  .idea/runConfigurations/Test_publication.xml
  buildSrc/src/main/kotlin/jewel.gradle.kts
  gradle.properties
Labels: feature

#485 Rename optimizeEdits to editorMode in MarkdownProcessor
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessorOptimizeEditsTest.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: api, markdown

#482 Improve and update Markdown readme
  markdown/README.md
Labels: documentation, markdown

#499 Add script and instructions to generate better release notes
  .gitignore
  RELEASING.md
  generate-release-patch.sh
Labels: documentation

#502 Add basic shortcuts to Standalone L1 navigation screens
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/MainViewModel.kt
Labels: standalone, maintenance

#501 Add selectable and toggleable Icon(Action)Button
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/state/ToggleableComponentState.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/ComponentsView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Checkbox.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/IconActionButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/IconButton.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/IconButtonStyling.kt
Labels: new component, cleanup

#507 Improve IconKey API to include a classloader
  buildSrc/src/main/kotlin/icon-keys-generator.gradle.kts
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/icon/IntelliJIconKey.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiCheckboxStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiRadioButtonStyling.kt
  markdown/extension/gfm-alerts/api/gfm-alerts.api
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertBlockRenderer.kt
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertIcons.kt
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertStyling.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/extensions/github/alerts/BridgeGitHubAlertStyling.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/extensions/github/alerts/IntUiGitHubAlertStyling.kt
  samples/ide-plugin/src/main/kotlin/icons/IdeSampleIconKeys.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/reflection/Views.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Icon.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/icon/IconKey.kt
Labels: feature, api

#505 Remove Debug mode
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/Debug.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/util/JewelLogger.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgePainterHintsProvider.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/StandalonePainterHintsProvider.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
Labels: cleanup
