Repository JetBrains/jewel, pull requests merged in 2024-09, with the labels that each got.

#575 Bump IJP version to 242.21829.142 (242.1)
  gradle/libs.versions.toml
Labels: maintenance

#576 Use icon keys everywhere
  decorated-window/api/decorated-window.api
  decorated-window/src/main/kotlin/org/jetbrains/jewel/window/TitleBar.Linux.kt
  decorated-window/src/main/kotlin/org/jetbrains/jewel/window/styling/TitleBarStyling.kt
  int-ui/int-ui-decorated-window/api/int-ui-decorated-window.api
  int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/DecoratedWindowIconKeys.kt
  int-ui/int-ui-decorated-window/src/main/kotlin/org/jetbrains/jewel/intui/window/styling/IntUiTitleBarStyling.kt
  markdown/extension/gfm-alerts/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/github/alerts/GitHubAlertBlockRenderer.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Icon.kt
Labels: cleanup

#577 Simplify Node.readInlineContent() implementation
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/ProcessingUtil.kt
Labels: cleanup

#578 Remove one more usage of resource-based Icon APIs
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Dropdowns.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
Labels: cleanup

#580 Upgrade Compose to 1.7.0-beta01
  gradle/libs.versions.toml
Labels: maintenance

#581 Remove Jewel usages of deprecated PlatformIcon API
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Icons.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/PlatformIcon.kt
Labels: cleanup

#582 Update IJ Platform 233 to 233.8 (233.15619.7)
  gradle/libs.versions.toml
Labels: maintenance

#570 New SplitLayout
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/SplitLayouts.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/ComponentsViewModel.kt
  samples/standalone/src/main/resources/icons/components/splitLayout.svg
  samples/standalone/src/main/resources/icons/components/splitLayout_dark.svg
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SplitLayout.kt
Labels: bug, feature

#587 Use a line-height of 1.3x for the default text styles
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/Typography.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/TextStyles.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Typography.kt
Labels: consistency

#588 Create NoTheme JewelComposePanel versions
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
Labels: api, bridge

#593 Fix IconKeys generator task
  buildSrc/src/main/kotlin/icon-keys-generator.gradle.kts
  ui/api/ui.api
Labels: bug

#595 Update Compose to 1.7.0-beta02
  gradle/libs.versions.toml
  samples/standalone/build.gradle.kts
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
  ui/api/ui.api
  ui/build.gradle.kts
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/CircularProgressIndicator.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Icon.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/painter/ResourcePainterProvider.kt
Labels: maintenance

#598 Remove underline on unhovered Links
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/BridgeMarkdownStyling.kt
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
Labels: consistency

#592 Add syntax highlighting to markdown preview
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/code/MimeType.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/code/highlighting/CodeHighlighter.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/code/highlighting/NoOpCodeHighlighter.kt
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/code/highlighting/CodeHighlighterFactory.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/code/highlighting/LexerBasedCodeHighlighter.kt
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/MarkdownBlock.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/processing/MarkdownProcessor.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/MarkdownProcessorDocumentParsingTest.kt
  markdown/core/src/test/kotlin/org/jetbrains/jewel/markdown/TestUtils.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/BridgeProvideMarkdownStyling.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/IntUiProvideMarkdownStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindowFactory.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: feature

#606 Bump IJP to 242.22855.74 (242.2)
  gradle/libs.versions.toml
Labels: maintenance

#605 Minor code cleanup
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/TextStyles.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/Main.kt
Labels: cleanup

#615 Fix z-order for text field/area placeholder
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextField.kt
Labels: consistency

#619 Bump IJP Gradle plugin to 2.1.0
  gradle/libs.versions.toml
Labels: maintenance

#620 Rework SelectableLazyColumn
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/BasicSelectableLazyColumn.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/lazy/tree/BasicLazyTree.kt
  foundation/src/test/kotlin/org/jetbrains/jewel/foundation/lazy/SelectableLazyColumnTest.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/SelectableLazyColumn.kt
Labels: api
