Repository JetBrains/jewel, pull requests merged in 2024-06, with the labels that each got.

#392 Improve Markdown styling
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/JetBrainsMonoFont.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/TextStyles.kt
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Bold.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-BoldItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-ExtraBold.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-ExtraBoldItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-ExtraLight.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-ExtraLightItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Italic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Light.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-LightItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Medium.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-MediumItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Regular.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-SemiBold.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-SemiBoldItalic.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-Thin.ttf
  int-ui/int-ui-standalone/src/main/resources/fonts/jetbrains-mono/JetBrainsMono-ThinItalic.ttf
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/MarkdownStyling.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/BridgeMarkdownStyling.kt
  markdown/int-ui-standalone-styling/api/int-ui-standalone-styling.api
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
Labels: bug, feature

#393 Add editor & console text styles, use them in Markdown
  foundation/api/foundation.api
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/JewelTheme.kt
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/ThemeDefinition.kt
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiTheme.kt
  markdown/ide-laf-bridge-styling/api/ide-laf-bridge-styling.api
  markdown/ide-laf-bridge-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/bridge/styling/BridgeMarkdownStyling.kt
  markdown/int-ui-standalone-styling/src/main/kotlin/org/jetbrains/jewel/intui/markdown/standalone/styling/IntUiMarkdownStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Typography.kt
Labels: feature, api

#397 Fix Markdown styling usage, and add semantics support
  markdown/core/api/core.api
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/Markdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/Semantics.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/extensions/Markdown.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: bug

#400 Update target IJP to 241.17890.1
  gradle/libs.versions.toml
Labels: maintenance

#401 Update IntelliJ Platform target to 233.15325.26
  gradle/libs.versions.toml
Labels: maintenance

#403 Add PGP signing to publications
  .github/workflows/publish-hotfix.yml
  .github/workflows/publish.yml
  buildSrc/src/main/kotlin/jewel-publish.gradle.kts
Labels: feature

#407 Fix for `Snapshot publication is broken after adding PGP signing #405`
  .github/workflows/publish.yml
Labels: bug

#409 Fix TextArea layout
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextAreas.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
Labels: bug, consistency

#410 Add simple FocusOutline API
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/Outline.kt
Labels: feature, api

#408 Add default values to retrieve* functions
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
Labels: feature, api
