Repository JetBrains/jewel, pull requests merged in 2024-08, with the labels that each got.

#508 Upgrade IJP to 242.20224.159 (RC)
  gradle/libs.versions.toml
  samples/ide-plugin/build.gradle.kts
  samples/standalone/build.gradle.kts
  ui/src/test/kotlin/org/jetbrains/jewel/BasicJewelUiTest.kt
Labels: cleanup, maintenance

#516 Only apply workaround to CMP-5856 in toolwindows
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/JewelComposePanel.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/ToolWindowExtensions.kt
Labels: bug, release-blocker

#515 New iteration on scrollbars
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
  samples/standalone/src/main/resources/icons/components/scrollbar.svg
  samples/standalone/src/main/resources/icons/components/scrollbar_dark.svg
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/ScrollbarStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/TabStyling.kt
Labels: consistency

#519 Remove obsolete expui icons folder
  int-ui/int-ui-standalone/src/main/resources/expui/general/add.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/add_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronDown.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronDownLarge.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronDownLargeWhite.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronDownLarge_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronDown_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronLeft.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronLeft_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronRight.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronRight_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronUp.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronUpLarge.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronUpLarge_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/chevronUp_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/close.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/closeSmall.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/closeSmallHovered.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/closeSmallHovered_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/closeSmall_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/general/close_dark.svg
  int-ui/int-ui-standalone/src/main/resources/expui/ide/externalLink.svg
  int-ui/int-ui-standalone/src/main/resources/expui/ide/externalLink_dark.svg
Labels: cleanup

#520 Switch reflection-based system in standalone demo to simpler mechanism
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/StandaloneSampleIcons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/reflection/Views.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/ComponentsView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/MarkdownView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/WelcomeView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Borders.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Buttons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Checkboxes.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ChipsAndTree.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Dropdowns.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Icons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Links.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/ProgressBar.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/RadioButtons.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/SegmentedControls.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Slider.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tabs.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextAreas.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Tooltips.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/ComponentsViewModel.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/MainViewModel.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/viewmodel/ViewInfo.kt
Labels: standalone, cleanup, maintenance

#521 Clean up work on scrollbars
  .idea/inspectionProfiles/Project_Default.xml
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStyling.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindowFactory.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ScrollbarsShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/SwingComparisonTabPanel.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextAreas.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/TextFields.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextField.kt
Labels: consistency

#523 Make Studio releases task triggered on demand
  buildSrc/src/main/kotlin/android-studio-releases-generator.gradle.kts
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/demodata/AndroidStudioReleases.kt
  buildSrc/src/main/kotlin/org/jetbrains/jewel/buildlogic/demodata/AndroidStudioReleasesReader.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/JewelDemoToolWindowFactory.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/AndroidStudioReleases.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ApiLevelIndication.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ChannelIndication.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/DetailsPanel.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ImageComponent.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSamplePanel.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/UiInspectorUtil.kt
  samples/ide-plugin/src/main/resources/studio-splash-screens/Jellyfish-stable.png
  samples/ide-plugin/src/main/resources/studio-splash-screens/Koala-canary.png
  samples/ide-plugin/src/main/resources/studio-splash-screens/Koala-stable.png
  samples/ide-plugin/src/main/resources/studio-splash-screens/KoalaFeatureDrop-canary.png
  samples/ide-plugin/src/main/resources/studio-splash-screens/KoalaFeatureDrop-stable.png
  samples/ide-plugin/src/main/resources/studio-splash-screens/Ladybug-canary.png
Labels: cleanup

#524 Fix glitch in selected menu item background
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/state/FocusableComponentState.kt
Labels: bug, consistency

#526 Update IJP and IJP Gradle plugin
  gradle/libs.versions.toml
Labels: maintenance

#527 Bump IJP 241
  gradle/libs.versions.toml
Labels: maintenance

#531 Expose PopupProperties in PopupMenu
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Menu.kt
Labels: api

#537 Bump IJP to 241.19072.14 (241.6)
  gradle/libs.versions.toml
Labels: maintenance

#535 Add scrollbar style and behavior reactive update for Mac OS
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/MacScrollbarHelper.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
Labels: consistency, bridge

#539 Fix Markdown loading in standalone sample
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/MarkdownView.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
Labels: bug

#548 Exclude generated files from formatKotlinMain
  buildSrc/src/main/kotlin/jewel.gradle.kts
Labels: maintenance

#552 Improve OverrideDarkMode kdocs
  foundation/src/main/kotlin/org/jetbrains/jewel/foundation/theme/JewelTheme.kt
Labels: documentation

#546 Migrate TitleBarView to new Icon API
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/TitleBarView.kt
Labels: consistency, maintenance

#554 Reimplement/fix/complete implementation of scrollbars
  ide-laf-bridge/api/ide-laf-bridge.api
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/BridgeUtils.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/MacScrollbarHelper.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/ScrollbarHelper.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/SwingBridgeService.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
  int-ui/int-ui-standalone/api/int-ui-standalone.api
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTabStripScrollbarStyling.kt
  markdown/core/src/main/kotlin/org/jetbrains/jewel/markdown/rendering/DefaultMarkdownBlockRenderer.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ComponentShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/ScrollbarsShowcaseTab.kt
  samples/ide-plugin/src/main/kotlin/org/jetbrains/jewel/samples/ideplugin/releasessample/ReleasesSampleCompose.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/component/Scrollbars.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownEditor.kt
  samples/standalone/src/main/kotlin/org/jetbrains/jewel/samples/standalone/view/markdown/MarkdownPreview.kt
  ui/api/ui.api
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ScrollableContainer.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbar.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Scrollbars.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TabStrip.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/styling/ScrollbarStyling.kt
Labels: feature, consistency

#540 Iterate on TextField and TextArea focused state UI
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/IntUiBridge.kt
  ide-laf-bridge/src/main/kotlin/org/jetbrains/jewel/bridge/theme/ScrollbarBridge.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiScrollbarStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextAreaStyling.kt
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/styling/IntUiTextFieldStyling.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/InputField.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/ScrollableContainer.kt
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextArea.kt
Labels: consistency

#567 Fix TextField placeholder going outside the bounds of the TextField
  ui/src/main/kotlin/org/jetbrains/jewel/ui/component/TextField.kt
Labels: bug

#569 Fix global border colors
  int-ui/int-ui-standalone/src/main/kotlin/org/jetbrains/jewel/intui/standalone/theme/IntUiGlobalColors.kt
Labels: bug
